twig:
    file_name_pattern: '*.twig'
#    form_themes: [ 'form_theme.html.twig' ]
#    - [ 'bootstrap_5_layout.html.twig' ]
#    - ['form_theme.html.twig']

when@test:
    twig:
        strict_variables: true
